name: CPP Context Verify & Validation

# Need to update this for actual migration
trigger:
  branches:
    include:
      - master
      - 'team/*'
  paths:
    include:
      - '*'

pr:
  - '*'

resources:
  repositories:
    - repository: cppAzureDevOpsTemplates
      type: github
      name: hmcts/cpp-azure-devops-templates
      endpoint: 'hmcts'
      ref: 'main'

pool:
  name: "MDV-ADO-AGENT-AKS-01"
  demands:
    - identifier -equals ubuntu-j21

stages:
    - template: pipelines/vp-build.yaml@cppAzureDevOpsTemplates
      parameters:
        repo: "$(Build.Repository.Name)"

