server:
  shutdown: "graceful"
  port: ${SERVER_PORT:4550}

management:
  server:
    # Keep actuator on same port by default; override if you want a separate port
    port: ${MANAGEMENT_SERVER_PORT:${SERVER_PORT:4550}}
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      probes:
        enabled: true                  # liveness/readiness groups
  metrics:
    tags:
      service: service-hmcts-springboot-template
      cluster: ${CLUSTER_NAME:local}
      region: ${REGION:local}
  tracing:
    sampling:
      probability: ${TRACING_SAMPLER_PROBABILITY:1.0}
  otlp:
    tracing:
      endpoint: ${OTEL_TRACES_URL:http://localhost:4318/v1/traces}
    metrics:
      export:
        enabled: ${OTEL_METRICS_ENABLED:false}
        url: ${OTEL_METRICS_URL:http://localhost:4318/v1/metrics}

# Temporarily commented out due to SpringDoc compatibility issues with Spring Boot 4.0.0-M3
# springdoc:
#   packagesToScan: uk.gov.hmcts.cp.controllers
#   writer-with-order-by-keys: true

# Disable SpringDoc auto-configuration
spring:
  autoconfigure:
    exclude: org.springdoc.core.configuration.SpringDocKotlinConfiguration
  config:
    import: "optional:configtree:/mnt/secrets/rpe/"
  application:
    name: service-UPDATE-TO-BE-NAME-OF-SERVICE
#  azure:
#    cosmos:
#      endpoint: ${COSMOSDB_ENDPOINT}
#      key: ${COSMOSDB_KEY}
#      database: ${COSMOSDB_DATABASE}

azure:
  application-insights:
    instrumentation-key: ${rpe.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

jwt:
  # Expose upwards to allow env var override: export JWT_SECRET_KEY=... (base64, 256-bit min)
  secretKey: ${JWT_SECRET_KEY:it-must-be-a-string-secret-at-least-256-bits-long}
  filter:
    enabled: false

logging:
  level:
    root: INFO
  # Use your JSON config (async) — make sure this file exists
  config: classpath:logback.xml

# Optional: Java 21 virtual threads (Boot 3.2+ / 4.x)
spring.threads.virtual.enabled: ${VIRTUAL_THREADS:false}