services:
  db:
    image: postgres:16-alpine
    container_name: sbt_CP_CDK_DB_it
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 30

  app:
    container_name: sbt_app_it
    build:
      context: ..                # project root (so Docker has access to source)
      dockerfile: docker/Dockerfile
    ports:
      - "4550:4550"
    environment:
      CP_CDK_DATASOURCE_URL: jdbc:postgresql://db:5432/appdb
      CP_CDK_DATASOURCE_USERNAME: app
      CP_CDK_DATASOURCE_PASSWORD: app
      SERVER_PORT: 4550
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4550/actuator/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 12