name: Secrets Scanner
on:
  pull_request:
    branches:
      - master
      - main
  schedule:
    - cron: '0 4 * * 4' # Every Thursday at 04:00
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: hmcts/secrets-scanner@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gitleaks_license: ${{ secrets.GITLEAKS_LICENSE }}
          gitleaks_regex_internal_url: ${{ secrets.HMCTS_CP_GITLEAKS_REGEX_INTERNAL_URL }}
